package com.graduate.springboot.Dao;

import com.graduate.springboot.Dao.entity.Notice;

import java.util.List;

public interface NoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated
     */
    int insertSelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated
     */
    Notice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Notice record);
    List<Notice> selectNotice();
    List<Notice> selectNoTopfour();
    List<Notice> selectNoTopTen();
    List<Notice> selectNoTopTenByType(String type);
    List<Notice> selectNoTenByTypeAndPageNum(String type, int pageNum, String noticedatetime);
    List<Notice> selectNoTenByPageNum(int pageNum, String noticedatetime);
    List<Notice> selectNoDetail(int id);
    List<Notice> selectNoticeByPageAndLimit(int page, int limit);
    void autoIncrement();
}