package com.graduate.springboot.Dao;

import com.graduate.springboot.Dao.entity.Candidate;

import java.util.List;

public interface CandidateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate_info
     *
     * @mbg.generated
     */
    int insert(Candidate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate_info
     *
     * @mbg.generated
     */
    int insertSelective(Candidate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate_info
     *
     * @mbg.generated
     */
    Candidate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Candidate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table candidate_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Candidate record);
    List<Candidate>selectByOpenid(String openid);
    int updateByOpenId(Candidate candidate);
    List<Candidate>selectByIdNumber(String candidateIdnumber);
    int insertNoRepeatInfo(Candidate candidate);
    void autoIncrement();
    Void inserttest();
    List<Candidate>selectByPage(int pagenum,int limit);
    List<Candidate>getallcandi();
    int adminInsertCandi( Candidate candidate);
    int deleteByPrimaryKey(int id);
}