package com.graduate.springboot.Dao.entity;

import java.io.Serializable;

public class Candidate implements Serializable {
    private static final long serialVersionUID =1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate_info.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate_info.candidate_name
     *
     * @mbg.generated
     */
    private String candidateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate_info.candidate_phone
     *
     * @mbg.generated
     */
    private String candidatePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate_info.candidate_age
     *
     * @mbg.generated
     */
    private Integer candidateAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate_info.candidate_sex
     *
     * @mbg.generated
     */
    private String candidateSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate_info.candidate_idnumber
     *
     * @mbg.generated
     */
    private String candidateIdnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate_info.candidate_ncee_score
     *
     * @mbg.generated
     */
    private Integer candidateNceeScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate_info.candidate_ncee_wish
     *
     * @mbg.generated
     */
    private String candidateNceeWish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate_info.candidate_nativeplace
     *
     * @mbg.generated
     */
    private String candidateNativeplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate_info.candidate_birthday
     *
     * @mbg.generated
     */
    private String candidateBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate_info.candidate_award
     *
     * @mbg.generated
     */
    private String candidateAward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate_info.candidate_email
     *
     * @mbg.generated
     */
    private String candidateEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate_info.id
     *
     * @return the value of candidate_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate_info.id
     *
     * @param id the value for candidate_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate_info.openid
     *
     * @return the value of candidate_info.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate_info.openid
     *
     * @param openid the value for candidate_info.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate_info.candidate_name
     *
     * @return the value of candidate_info.candidate_name
     *
     * @mbg.generated
     */
    public String getCandidateName() {
        return candidateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate_info.candidate_name
     *
     * @param candidateName the value for candidate_info.candidate_name
     *
     * @mbg.generated
     */
    public void setCandidateName(String candidateName) {
        this.candidateName = candidateName == null ? null : candidateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate_info.candidate_phone
     *
     * @return the value of candidate_info.candidate_phone
     *
     * @mbg.generated
     */
    public String getCandidatePhone() {
        return candidatePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate_info.candidate_phone
     *
     * @param candidatePhone the value for candidate_info.candidate_phone
     *
     * @mbg.generated
     */
    public void setCandidatePhone(String candidatePhone) {
        this.candidatePhone = candidatePhone == null ? null : candidatePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate_info.candidate_age
     *
     * @return the value of candidate_info.candidate_age
     *
     * @mbg.generated
     */
    public Integer getCandidateAge() {
        return candidateAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate_info.candidate_age
     *
     * @param candidateAge the value for candidate_info.candidate_age
     *
     * @mbg.generated
     */
    public void setCandidateAge(Integer candidateAge) {
        this.candidateAge = candidateAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate_info.candidate_sex
     *
     * @return the value of candidate_info.candidate_sex
     *
     * @mbg.generated
     */
    public String getCandidateSex() {
        return candidateSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate_info.candidate_sex
     *
     * @param candidateSex the value for candidate_info.candidate_sex
     *
     * @mbg.generated
     */
    public void setCandidateSex(String candidateSex) {
        this.candidateSex = candidateSex == null ? null : candidateSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate_info.candidate_idnumber
     *
     * @return the value of candidate_info.candidate_idnumber
     *
     * @mbg.generated
     */
    public String getCandidateIdnumber() {
        return candidateIdnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate_info.candidate_idnumber
     *
     * @param candidateIdnumber the value for candidate_info.candidate_idnumber
     *
     * @mbg.generated
     */
    public void setCandidateIdnumber(String candidateIdnumber) {
        this.candidateIdnumber = candidateIdnumber == null ? null : candidateIdnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate_info.candidate_ncee_score
     *
     * @return the value of candidate_info.candidate_ncee_score
     *
     * @mbg.generated
     */
    public Integer getCandidateNceeScore() {
        return candidateNceeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate_info.candidate_ncee_score
     *
     * @param candidateNceeScore the value for candidate_info.candidate_ncee_score
     *
     * @mbg.generated
     */
    public void setCandidateNceeScore(Integer candidateNceeScore) {
        this.candidateNceeScore = candidateNceeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate_info.candidate_ncee_wish
     *
     * @return the value of candidate_info.candidate_ncee_wish
     *
     * @mbg.generated
     */
    public String getCandidateNceeWish() {
        return candidateNceeWish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate_info.candidate_ncee_wish
     *
     * @param candidateNceeWish the value for candidate_info.candidate_ncee_wish
     *
     * @mbg.generated
     */
    public void setCandidateNceeWish(String candidateNceeWish) {
        this.candidateNceeWish = candidateNceeWish == null ? null : candidateNceeWish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate_info.candidate_nativeplace
     *
     * @return the value of candidate_info.candidate_nativeplace
     *
     * @mbg.generated
     */
    public String getCandidateNativeplace() {
        return candidateNativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate_info.candidate_nativeplace
     *
     * @param candidateNativeplace the value for candidate_info.candidate_nativeplace
     *
     * @mbg.generated
     */
    public void setCandidateNativeplace(String candidateNativeplace) {
        this.candidateNativeplace = candidateNativeplace == null ? null : candidateNativeplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate_info.candidate_birthday
     *
     * @return the value of candidate_info.candidate_birthday
     *
     * @mbg.generated
     */
    public String getCandidateBirthday() {
        return candidateBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate_info.candidate_birthday
     *
     * @param candidateBirthday the value for candidate_info.candidate_birthday
     *
     * @mbg.generated
     */
    public void setCandidateBirthday(String candidateBirthday) {
        this.candidateBirthday = candidateBirthday == null ? null : candidateBirthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate_info.candidate_award
     *
     * @return the value of candidate_info.candidate_award
     *
     * @mbg.generated
     */
    public String getCandidateAward() {
        return candidateAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate_info.candidate_award
     *
     * @param candidateAward the value for candidate_info.candidate_award
     *
     * @mbg.generated
     */
    public void setCandidateAward(String candidateAward) {
        this.candidateAward = candidateAward == null ? null : candidateAward.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate_info.candidate_email
     *
     * @return the value of candidate_info.candidate_email
     *
     * @mbg.generated
     */
    public String getCandidateEmail() {
        return candidateEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate_info.candidate_email
     *
     * @param candidateEmail the value for candidate_info.candidate_email
     *
     * @mbg.generated
     */
    public void setCandidateEmail(String candidateEmail) {
        this.candidateEmail = candidateEmail == null ? null : candidateEmail.trim();
    }
}