package com.graduate.springboot.Dao.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.no_title
     *
     * @mbg.generated
     */
    private String noTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.no_content
     *
     * @mbg.generated
     */
    private String noContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.no_author
     *
     * @mbg.generated
     */
    private String noAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.no_datetime
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date noDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.no_uploader
     *
     * @mbg.generated
     */
    private String noUploader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.no_type
     *
     * @mbg.generated
     */
    private String noType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.no_top
     *
     * @mbg.generated
     */
    private String noTop;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.no_title
     *
     * @return the value of notice.no_title
     *
     * @mbg.generated
     */
    public String getNoTitle() {
        return noTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.no_title
     *
     * @param noTitle the value for notice.no_title
     *
     * @mbg.generated
     */
    public void setNoTitle(String noTitle) {
        this.noTitle = noTitle == null ? null : noTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.no_content
     *
     * @return the value of notice.no_content
     *
     * @mbg.generated
     */
    public String getNoContent() {
        return noContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.no_content
     *
     * @param noContent the value for notice.no_content
     *
     * @mbg.generated
     */
    public void setNoContent(String noContent) {
        this.noContent = noContent == null ? null : noContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.no_author
     *
     * @return the value of notice.no_author
     *
     * @mbg.generated
     */
    public String getNoAuthor() {
        return noAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.no_author
     *
     * @param noAuthor the value for notice.no_author
     *
     * @mbg.generated
     */
    public void setNoAuthor(String noAuthor) {
        this.noAuthor = noAuthor == null ? null : noAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.no_datetime
     *
     * @return the value of notice.no_datetime
     *
     * @mbg.generated
     */
    public Date getNoDatetime() {
        return noDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.no_datetime
     *
     * @param noDatetime the value for notice.no_datetime
     *
     * @mbg.generated
     */
    public void setNoDatetime(Date noDatetime) {
        this.noDatetime = noDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.no_uploader
     *
     * @return the value of notice.no_uploader
     *
     * @mbg.generated
     */
    public String getNoUploader() {
        return noUploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.no_uploader
     *
     * @param noUploader the value for notice.no_uploader
     *
     * @mbg.generated
     */
    public void setNoUploader(String noUploader) {
        this.noUploader = noUploader == null ? null : noUploader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.no_type
     *
     * @return the value of notice.no_type
     *
     * @mbg.generated
     */
    public String getNoType() {
        return noType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.no_type
     *
     * @param noType the value for notice.no_type
     *
     * @mbg.generated
     */
    public void setNoType(String noType) {
        this.noType = noType == null ? null : noType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.no_top
     *
     * @return the value of notice.no_top
     *
     * @mbg.generated
     */
    public String getNoTop() {
        return noTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.no_top
     *
     * @param noTop the value for notice.no_top
     *
     * @mbg.generated
     */
    public void setNoTop(String noTop) {
        this.noTop = noTop == null ? null : noTop.trim();
    }
}